apiVersion: v1
kind: Service
metadata:
  name: growthbook
spec:
  selector:
    app: growthbook
  ports:
    - name: ui
      port: 3000
      targetPort: 3000
    - name: api
      port: 3100
      targetPort: 3100
