apiVersion: apps/v1
kind: Deployment
metadata:
  name: growthbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growthbook
  template:
    metadata:
      labels:
        app: growthbook
    spec:
      containers:
        - name: growthbook
          image: {{ .Values.growthbook.image }}
          ports:
            - containerPort: {{ .Values.growthbook.ports.ui }}
            - containerPort: {{ .Values.growthbook.ports.api }}
          env:
            - name: MONGODB_URI
              value: mongodb://{{ .Values.mongo.username }}:{{ .Values.mongo.password }}@mongo:27017/{{ .Values.mongo.database }}?authSource=admin
