apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinot
  labels:
    app: pinot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinot
  template:
    metadata:
      labels:
        app: pinot
    spec:
      containers:
        - name: pinot
          image: apachepinot/pinot
          ports:
            - containerPort: 8089