apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  namespace: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
      - name: trino
        image: your-docker-repo/trino:latest
        ports:
        - containerPort: 8080
